Add Fleet documentation
suse-edge/suse-edge.github.io pull request #130
Opened 2024-03-25 11:07 UTC by jtomasek

2024-03-25 14:07 UTC, agracey requested changes
Thank you for this! 

I added a few comments to make sure we don't fall into similar traps as we have in the past.

2024-03-25 14:07 UTC, agracey commented on asciidoc/components/fleet.adoc
> +:imagesdir: ../images/
I don't think this needs to be redefined?

2024-03-25 14:07 UTC, agracey commented on asciidoc/components/fleet.adoc
> +Fleet is a separate project from Rancher, and can be https://fleet.rancher.io/installation[installed] on any Kubernetes cluster with Helm.
Since most people will have Fleet already installed with Rancher, it might be best to say something like "Fleet comes built in to Rancher but if you want to install it standalone: [...]"

2024-03-25 14:07 UTC, agracey commented on asciidoc/components/fleet.adoc
> +Rancher uses Fleet to deploy applications across managed clusters. Continuous delivery with Fleet introduces GitOps at scale, designed to manage applications running on up to a million clusters.
"a million" -> "large numbers of"

2024-03-25 14:07 UTC, agracey commented on asciidoc/components/fleet.adoc
> +== Example of installing KubeVirt with Rancher and Fleet using Rancher Dashboard
Great choice of example!

2024-03-25 15:01 UTC, jtomasek commented on asciidoc/components/fleet.adoc
> +:imagesdir: ../images/
I've used VSCode asciidoc plugin to get the preview when writing the doc and in that case the configuration did not get used due to `ifdef::env-github[]` on line 4. I assume that if we use github workflows to build the docs this re-definition can be removed. Yes.

2024-03-25 17:06 UTC, agracey commented on asciidoc/components/fleet.adoc
> +:imagesdir: ../images/
What I don't know is if it'll break anything with the "production" build. Leave it for now and I'll test once merged

2024-03-26 10:24 UTC, jtomasek commented on asciidoc/components/fleet.adoc
> +Fleet is a separate project from Rancher, and can be https://fleet.rancher.io/installation[installed] on any Kubernetes cluster with Helm.
Done.

2024-03-26 10:24 UTC, jtomasek commented on asciidoc/components/fleet.adoc
> +Rancher uses Fleet to deploy applications across managed clusters. Continuous delivery with Fleet introduces GitOps at scale, designed to manage applications running on up to a million clusters.
Done.

2024-03-26 14:36 UTC, agracey approved these changes

2024-03-26 14:36 UTC, merged