added docs for mgmt-cluster
suse-edge/suse-edge.github.io pull request #271
Opened 2024-05-20 10:28 UTC by alknopfler

- Added new way to deploy mgmt-cluster explaining the HA and the new manifests introduced to improve this part.

2024-05-20 12:48 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +Also, as a prerequisite to deploy a management cluster you will need to reserve 3 IPs in your network:
changed

2024-05-20 12:50 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> -==== Image section:
Because we cannot use more levels (like 5 =====), and following the sections we're using ==== for the main section blocks, so to explain the content inside we used bad the first time

2024-05-20 12:55 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +==== Custom folder:
let's talk about the structure. This is what I think should be the structure (before IMHO was confused)
=== instroduction
=== Steps to set up the management cluster
=== Image preparation
       ==== Directory Structure
       ==== Management cluster definition file
       ==== Custom Folder
       ==== Kubernetes Folder
       ==== Networking Folder
=== Image Creation

2024-05-21 05:07 UTC, ranjinimn commented
@dariavladykina Can you please review this PR ?

2024-05-21 07:46 UTC, alknopfler commented
@ranjinimn I've updated creating a basic index in the first part of the document doing some references to the specific sections explained after that. 
Thanks for your feedback

2024-05-21 09:42 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +The name of the file has to match the hostname defined in the `mgmt-cluster.yaml` definition file into the network/node section described above.
done

2024-05-21 10:49 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
> +* **xref:mgmt-cluster-image-preparation[Image preparation]**: The first step is to prepare the manifests and files with all the necessary configurations.
````
. **xref:mgmt-cluster-image-preparation[Image preparation]**: The first step is to prepare the manifests and files with all the necessary configurations.
````

2024-05-21 10:49 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
>  There are two main steps to set up the management cluster using a declarative approach:
In this case, since we have divided into 3 steps, This will change to: 
````
There are three steps to set up the management cluster using a declarative approach:
````

2024-05-21 10:49 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
> +* **xref:mgmt-cluster-image-creation[Image creation]**: This step covers the creation of the image using the `Edge Image Builder` tool. This step can be done using a laptop, server, VM or any other x
````
. **xref:mgmt-cluster-image-creation[Image creation]**: This step covers the creation of the image using the `Edge Image Builder` tool. This step can be done using a laptop, server, VM or any other x86_64 system with a container runtime installed.
````

2024-05-21 10:49 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
Suggestion: The 3rd step can be mentioned here that once the image is created, you can set up the management cluster and provide the step.  

````
. **Set up the management cluster**. 
````
````

2024-05-21 11:10 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
> +- `rancher.yaml`: contains the configuration to create the `Rancher` component. The `$\{INGRESS_VIP\}` has to be set properly to define the IP address to be consumed by the `Rancher` component. The U
````
- `rancher.yaml`: contains the configuration to create the `Rancher` component. The `$\{INGRESS_VIP\}` has to be set properly to define the IP address to be consumed by the `Rancher` component. The URL to access the `Rancher` component is `https://rancher-$\{INGRESS_VIP\}.sslip.io`.
+
[,yaml]
````

2024-05-21 11:10 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
> +- `neuvector.yaml`: contains the configuration to create the `NeuVector` component (no modifications needed).
````
- `neuvector.yaml`: contains the configuration to create the `NeuVector` component (no modifications needed).
+
[,yaml]
````

2024-05-21 11:10 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
> +- `metal3.yaml`: contains the configuration to create the `Metal^3^` component. The `$\{METAL3_VIP\}` has to be set properly to define the IP address to be consumed by the `Metal^3^` component.
````
- `metal3.yaml`: contains the configuration to create the `Metal^3^` component. The `$\{METAL3_VIP\}` has to be set properly to define the IP address to be consumed by the `Metal^3^` component.
+
[,yaml]
````

2024-05-21 11:10 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
> +- add the `enable_metal3_media_server` to `true` to enable the media server feature in the global section.
````
- Add the `enable_metal3_media_server` to `true` to enable the media server feature in the global section.
- Include the following configuration about the media server where $\{MEDIA_VOLUME_PATH\} is the path to the media volume in the media (e.g `/home/metal3/bmh-image-cache`)
+
[,yaml]
````

2024-05-21 11:10 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
> +- `certmanager.yaml`: contains the configuration to create the `Cert-Manager` component (no modifications needed).
````
- `certmanager.yaml`: contains the configuration to create the `Cert-Manager` component (no modifications needed).
+
[,yaml]
````

2024-05-21 11:10 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
> +- Depending on the number of nodes in the management cluster, you can create more files like `mgmt-cluster-node2.yaml`, `mgmt-cluster-node3.yaml`, etc. to configure properly the rest of the nodes.
````
- Depending on the number of nodes in the management cluster, you can create more files like `mgmt-cluster-node2.yaml`, `mgmt-cluster-node3.yaml`, etc. to configure the rest of the nodes.
````

2024-05-21 11:10 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
> +- The examples contain a static IP configuration, but you can also use DHCP by setting `dhcp: true` in the `ipv4` section (uncomment the lines).
Just  a question for my understanding: 
Here, does the user need to uncomment "## interfaces" line?

2024-05-21 11:10 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
> +
you can remove these lines below 1004 as they do not have any content.

2024-05-21 11:55 UTC, ranjinimn commented on asciidoc/product/atip-management-cluster.adoc
> +        ** xref:mgmt-cluster-kubernetes-definition-file[Kubernetes] version with the Helm charts to be installed, the repositories to be used, the network configuration, and the nodes to be used in t
The PDF rendered is looking for a title for Image information, Operating System, and Kubernetes. 

![image](https://github.com/suse-edge/suse-edge.github.io/assets/168088002/619dcbb2-9a43-4f6f-8d6e-c601245a23a2)

2024-05-21 14:12 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +- Depending on the number of nodes in the management cluster, you can create more files like `mgmt-cluster-node2.yaml`, `mgmt-cluster-node3.yaml`, etc. to configure properly the rest of the nodes.
which is the suggestion?

2024-05-21 14:12 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +* **xref:mgmt-cluster-image-preparation[Image preparation]**: The first step is to prepare the manifests and files with all the necessary configurations.
which is the suggestion?

2024-05-21 14:17 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +        ** xref:mgmt-cluster-kubernetes-definition-file[Kubernetes] version with the Helm charts to be installed, the repositories to be used, the network configuration, and the nodes to be used in t
maybe because it's not a title? let's remove then the ref

2024-05-21 14:22 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +- The examples contain a static IP configuration, but you can also use DHCP by setting `dhcp: true` in the `ipv4` section (uncomment the lines).
good catch, the last line in the note has to be deleted. Thanks

2024-05-21 15:51 UTC, hardys commented on asciidoc/product/atip-management-cluster.adoc
> +----
With this change I think we can mark this PR as resolving https://github.com/suse-edge/suse-edge.github.io/issues/270 ?

2024-05-22 06:55 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +----
I think so

2024-05-22 06:58 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +* **xref:mgmt-cluster-image-preparation[Image preparation]**: The first step is to prepare the manifests and files with all the necessary configurations.
now I know...means secuence instead of bullets. Thanks a lot @ranjinimn

2024-05-22 07:05 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +----
reviewed also with @ranjinimn.

2024-05-22 10:20 UTC, dariavladykina reviewed
Hi, please see some suggestions and comments after a language review. Thanks!

2024-05-22 10:20 UTC, dariavladykina commented on asciidoc/product/atip-management-cluster.adoc
> +# It requires rke2 or k3s running, but it won't fail if those services are not present
```suggestion
# It requires rke2 or k3s running, but it will not fail if those services are not present
```

2024-05-22 10:20 UTC, dariavladykina commented on asciidoc/product/atip-management-cluster.adoc
> +- `rancher.yaml`: contains the configuration to create the `Rancher` component. The `$\{INGRESS_VIP\}` has to be set properly to define the IP address to be consumed by the `Rancher` component. The U
```suggestion
- `rancher.yaml`: contains the configuration to create the `Rancher` component. The `$\{INGRESS_VIP\}` must be set properly to define the IP address to be consumed by the `Rancher` component. The URL to access the `Rancher` component will be `https://rancher-$\{INGRESS_VIP\}.sslip.io`.
```

2024-05-22 10:20 UTC, dariavladykina commented on asciidoc/product/atip-management-cluster.adoc
> +- `server.yaml`: By default, the `CNI` plugin installed by default is `Cilium`, so you do not need to create this folder and file. Just in case you need to customize the `CNI` plugin, you can use the
```suggestion
- `server.yaml`: By default, the `CNI` plug-in installed by default is `Cilium`, so you do not need to create this folder and file. Just in case you need to customize the `CNI` plug-in, you can use the `server.yaml` file under the `kubernetes/config` folder. It contains the following information:
```

2024-05-22 10:20 UTC, dariavladykina commented on asciidoc/product/atip-management-cluster.adoc
> +- `metal3.yaml`: contains the configuration to create the `Metal^3^` component. The `$\{METAL3_VIP\}` has to be set properly to define the IP address to be consumed by the `Metal^3^` component.
```suggestion
- `metal3.yaml`: contains the configuration to create the `Metal^3^` component. The `$\{METAL3_VIP\}` must be set properly to define the IP address to be consumed by the `Metal^3^` component.
```

2024-05-22 10:20 UTC, dariavladykina commented on asciidoc/product/atip-management-cluster.adoc
> +The Media Server is an optional feature included in Metal^3^ (by default is disabled). To use the Metal3 feature you need to  on the previous manifest.
```suggestion
The Media Server is an optional feature included in Metal^3^ (by default is disabled). To use the Metal3 feature, you need to  on the previous manifest.
```

2024-05-22 10:20 UTC, dariavladykina commented on asciidoc/product/atip-management-cluster.adoc
> +The Media Server is an optional feature included in Metal^3^ (by default is disabled). To use the Metal3 feature you need to  on the previous manifest.
There seems to be a word missing after "need to".

2024-05-22 10:20 UTC, dariavladykina commented on asciidoc/product/atip-management-cluster.adoc
> +The name of the file has to match the hostname defined in the `mgmt-cluster.yaml` definition file into the network/node section described above.
```suggestion
The name of the file must match the host name defined in the `mgmt-cluster.yaml` definition file into the network/node section described above.
```

2024-05-22 10:20 UTC, dariavladykina commented on asciidoc/product/atip-management-cluster.adoc
> +In case you want to use DHCP to get the IP address, you can use the following configuration (the `MAC` address has to be set properly using the `$\{MGMT_MAC\}` variable):
```suggestion
If you want to use DHCP to get the IP address, you can use the following configuration (the `MAC` address must be set properly using the `$\{MGMT_MAC\}` variable):
```

2024-05-22 10:20 UTC, dariavladykina commented on asciidoc/product/atip-management-cluster.adoc
>  The image `SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM2.install.iso` has to be downloaded from the https://scc.suse.com/[SUSE Customer Center] or the https://www.suse.com/download/sle-micro/[SUSE D
```suggestion
The image `SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM2.install.iso` must be downloaded from the https://scc.suse.com/[SUSE Customer Center] or the https://www.suse.com/download/sle-micro/[SUSE Download page], and it must be located under the `base-images` folder.
```

2024-05-22 10:20 UTC, dariavladykina commented on asciidoc/product/atip-management-cluster.adoc
> +- `ingress-ippool.yaml`: contains the configuration to create the `IPAddressPool` for the `MetalLB` component. The `$\{INGRESS_VIP\}` has to be set properly to define the IP address reserved to be us
```suggestion
- `ingress-ippool.yaml`: contains the configuration to create the `IPAddressPool` for the `MetalLB` component. The `$\{INGRESS_VIP\}` must be set properly to define the IP address reserved to be used by the `MetalLB` component.
```

2024-05-22 10:20 UTC, dariavladykina commented on asciidoc/product/atip-management-cluster.adoc
> +  # Don't create the ippool if already created
```suggestion
  # Do not create the ippool if already created
```

2024-05-22 12:17 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +The Media Server is an optional feature included in Metal^3^ (by default is disabled). To use the Metal3 feature you need to  on the previous manifest.
configure it. Added

2024-05-22 12:20 UTC, alknopfler commented
@dariavladykina changes done. 
thanks for your help

2024-05-22 15:50 UTC, hardys approved these changes

2024-05-22 15:56 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +  - xref:mgmt-cluster-directory-structure[Directory structure]: The first step is to create a directory structure to be used by `Edge Image Builder` to store the configuration files and the image its
two first steps?

2024-05-22 16:11 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +  - xref:mgmt-cluster-custom-folder[Custom folder]: The `custom` folder contains the configuration files and scripts to be used by the management cluster.
```suggestion
  - xref:mgmt-cluster-custom-folder[Custom folder]: The `custom` folder contains the configuration files and scripts used by EIB to deploy a fully functional management cluster.
```

2024-05-22 16:13 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +Also, as a prerequisite to deploy a management cluster, you need to reserve three IPs in your network:
```suggestion
Also, as a prerequisite to deploy a highly available management cluster, you need to reserve three IPs in your network:
```

2024-05-22 16:14 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +The image `SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM2.install.iso` must be downloaded from the https://scc.suse.com/[SUSE Customer Center] or the https://www.suse.com/download/sle-micro/[SUSE Dow
We now have the SHA256 sums in the release notes. It would be nice to ask users to verify those just in case.

2024-05-22 16:14 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +An example of the directory structure can be found in the https://github.com/suse-edge/misc/tree/main/telco-examples[GitHub repository Telco Examples].
```suggestion
An example of the directory structure can be found in the https://github.com/suse-edge/misc/tree/main/telco-examples[SUSE Edge GitHub repository under the "telco-examples" folder].
```

2024-05-22 16:15 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +where the `installDevice` is the device to be used to install the operating system, the `username` and `encryptedPassword` are the credentials to be used to access the system, the `packageList` is th
```suggestion
where the `installDevice` is the device to be used to install the operating system, the `username` and `encryptedPassword` are the credentials to be used to access the system, the `packageList` is the list of packages to be installed (`jq` is required internally during the installation process), and the `sccRegistrationCode` is the registration code used to get the packages and dependencies at build time and can be obtained from the SUSE Customer Center.
```

2024-05-22 16:17 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +The `apiVIP` should be an IP address that is not used in the network and is not part of the DHCP pool (in case we use DHCP). Also, when we use the `apiVIP` in a multi-node cluster, it is used to acce
```suggestion
The `apiVIP` should be an IP address that is not used in the network and should not be part of the DHCP pool (in case we use DHCP). Also, when we use the `apiVIP` in a multi-node cluster, it is used to access the Kubernetes API server.
```

2024-05-22 16:17 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +The `nodes` section contains the list of nodes to be used in the cluster. In our case, we are using a single-node cluster, but it can be extended to a multi-node cluster by adding more nodes to the l
```suggestion
The `nodes` section contains the list of nodes to be used in the cluster. In this example, a single-node cluster is being used, but it can be extended to a multi-node cluster by adding more nodes to the list (by uncommenting the lines).
```

2024-05-22 16:19 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +[,shell]
I'd say it would be nice to add a note here that in the future this won't be needed by replacing those scripts by the rancher-turtles thing.

2024-05-22 16:21 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +- `ingress-ippool.yaml`: contains the configuration to create the `IPAddressPool` for the `MetalLB` component. The `$\{INGRESS_VIP\}` has to be set properly to define the IP address reserved to be us
```suggestion
- `ingress-ippool.yaml`: contains the configuration to create the `IPAddressPool` for the `rke2-ingress-nginx` component. The `$\{INGRESS_VIP\}` has to be set properly to define the IP address reserved to be used by the `rke2-ingress-nginx` component.
```

2024-05-22 16:22 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +
You need to add the ipaddresspool and l2adv for the ironic service.

2024-05-22 16:22 UTC, e-minguez requested changes
Some changes requested.

2024-05-23 05:41 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +  - xref:mgmt-cluster-directory-structure[Directory structure]: The first step is to create a directory structure to be used by `Edge Image Builder` to store the configuration files and the image its
ok let's change it to say simply to create

2024-05-23 05:48 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +The image `SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM2.install.iso` must be downloaded from the https://scc.suse.com/[SUSE Customer Center] or the https://www.suse.com/download/sle-micro/[SUSE Dow
good idea... Added

2024-05-23 05:53 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +The `nodes` section contains the list of nodes to be used in the cluster. In our case, we are using a single-node cluster, but it can be extended to a multi-node cluster by adding more nodes to the l
yes much better explained. Thanks

2024-05-23 05:55 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +[,shell]
I prefer keep it as is for now.

2024-05-23 05:56 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +- `ingress-ippool.yaml`: contains the configuration to create the `IPAddressPool` for the `MetalLB` component. The `$\{INGRESS_VIP\}` has to be set properly to define the IP address reserved to be us
good catch

2024-05-23 05:57 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +
This is included in the metal3.sh script you created xDDDD

2024-05-23 05:59 UTC, alknopfler commented
@e-minguez thanks for your review as always! Changes done

2024-05-23 09:15 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +
I'm just stupid

2024-05-23 09:16 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +[,shell]
I'm not saying to remove anything but just add a note for users for them to know that in the future it will be simpler.

2024-05-23 09:19 UTC, e-minguez commented on asciidoc/product/atip-management-cluster.adoc
> +. **xref:mgmt-cluster-image-creation[Image creation]**: This step covers the creation of the image using the Edge Image Builder tool. This step can be done using a laptop, server, VM or any other x86
EIB prerequisites mention only SLES leap or tumbleweed https://documentation.suse.com/suse-edge/3.0/html/edge/quickstart-eib.html#id-prerequisites-2

2024-05-23 09:22 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +. **xref:mgmt-cluster-image-creation[Image creation]**: This step covers the creation of the image using the Edge Image Builder tool. This step can be done using a laptop, server, VM or any other x86
why not? using podman on windows ?

2024-05-23 09:56 UTC, e-minguez approved these changes

2024-05-23 11:30 UTC, merged