Add a quickstart about OBS packaging
suse-edge/suse-edge.github.io pull request #31
Opened 2023-05-09 08:55 UTC by diconico07

This quickstart aims to help start creating RPM packages and container images in OBS, only OBS specific topics are to be covered in this document.

2023-05-09 10:04 UTC, e-minguez requested changes
I've added some suggestions/changes PTAL :)

2023-05-09 12:48 UTC, diconico07 commented on docs/quickstart/create-package-obs.mdx
> +---
What would you see for a new section ? Developer how-to ?

2023-05-09 14:32 UTC, e-minguez commented on docs/quickstart/create-package-obs.mdx
> +---
That looks like a good one :)

2023-05-10 10:02 UTC, e-minguez approved these changes

2023-05-10 10:02 UTC, merged