Elemental quickstart: Remove Windows and more
suse-edge/suse-edge.github.io pull request #374
Opened 2024-09-16 02:10 UTC by jiwonhu

* Remove the instructions for Windows which is unsupported platform
* Update the required resources from 3 hosts to 2 hosts. EIB can run on management node. This is to make quickstart simple to lower the entry barrier for first timers
* Add the missing prerequisite of SLE Micro base image
* Bump up the key steps in subsub-sections to sub-sections. This makes the key steps appear on table of content, which increases readability.

Previous table of content:
<img width="211" alt="Screenshot 2024-09-16 at 9 17 23 AM" src="https://github.com/user-attachments/assets/02d4fbc4-dfcd-4940-9656-6e14d892e6dc">

With this update:
<img width="212" alt="Screenshot 2024-09-16 at 9 26 01 AM" src="https://github.com/user-attachments/assets/b060f671-c295-4e0f-8a03-fe7e32d3ab30">

2024-09-16 10:21 UTC, hardys commented on asciidoc/quickstart/elemental.adoc
> +* A host for the centralized management cluster (the one hosting Rancher, Elemental and Edge Image Builder):
Edge Image Builder doesn't necessarily run on the management cluster, since users might have access to the management cluster APIs without having access to run tools like EIB on the OS directly - this would be best-practice in all production situations IMO, since you will want to strictly limit admin access to the management cluster hosts.

So perhaps add a new line with something like "A host to run Edge Image Builder (can be a management cluster host in development scenarios)"?

2024-09-16 10:22 UTC, hardys commented on asciidoc/quickstart/elemental.adoc
> +== Node Reset (Recommended)
What's the context for the Recommended qualifier here?

2024-09-16 10:23 UTC, hardys commented
Overall looks good, thanks!  A couple of small comments and please could you rebase since https://github.com/suse-edge/suse-edge.github.io/pull/372 merged and contained some overlapping changes.

2024-09-16 10:52 UTC, jiwonhu commented on asciidoc/quickstart/elemental.adoc
> +== Node Reset (Recommended)
Will update to "Optional" as intended :-)

2024-09-16 11:49 UTC, jiwonhu commented
@hardys Revived the EIB host requirement and incorporated the feedback. Appreciate the review!

2024-09-17 20:34 UTC, hardys approved these changes
lgtm, thanks!

2024-09-17 20:36 UTC, hardys commented
Thanks @jiwonhu - we can squash-merge this but note in future you may like to use `git rebase -i origin` to rebase vs creating a merge commit, let me know if I can provide any help with that.

2024-09-17 20:42 UTC, hardys requested changes
Actually I see there's an issue with your git client configuration, because the author is `Jiwon Hu <jhu@Jiwons-MacBook-Pro.local>`

To resolve this you can do something like:

```
git config --global user.email "email_address"
git rebase -i origin  # squash the commits into one with the "squash" option
git commit --amend --author
```

Then you can force-push to your fork (in future I'd suggest using a branch instead of main so you can easily create multiple PRs)

2024-09-18 03:03 UTC, jiwonhu commented
@hardys I updated the author of my 2 commits [29945f5](https://github.com/suse-edge/suse-edge.github.io/pull/374/commits/29945f5f575a6a522cd6726ce5b34bee63a89e45) and [3f6e0da](https://github.com/suse-edge/suse-edge.github.io/pull/374/commits/3f6e0da0db57ea75ed1601fb6419149b719373dd). I hope this is okay now...?

2024-09-20 08:16 UTC, hardys commented
Hi @jiwonhu - sorry for the slow response - this is still hard to review because it's got 6 commits including merge commits, the way to fix that is:

```
git fetch -va
git rebase -i origin
```

If you have to fix any conflicts during the rebase, open the file mentioned and look for `HEAD`, then when resolved do:

```
git add <conflicting file>
git rebase --continue
```

Happy to chat about this and help next week if necessary! :)

2024-09-26 11:58 UTC, rdoxenham commented
@jiwonhu do you think we can merge this? Thanks!

2024-09-30 08:35 UTC, hardys approved these changes

2024-09-30 10:46 UTC, merged