Update Dashboard extensions documentation with OCI installation via Rancher UI
suse-edge/suse-edge.github.io pull request #375
Opened 2024-09-16 11:03 UTC by jtomasek

2024-09-23 08:33 UTC, hardys approved these changes

2024-09-23 09:14 UTC, ranjinimn reviewed
I have completed my review and I had a few suggestions. Once they are incorporated, I will be happy to review again.

2024-09-23 09:14 UTC, ranjinimn commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +2. On the Extensions page click the three dot menu at the top right and select *Manage Repositories*
```suggestion
2. On the Extensions page, click the three dot menu at the top right and select *Manage Repositories*.
```

2024-09-23 09:14 UTC, ranjinimn commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +Each extension is distributed via it's own OCI artefact. Therefore it is required to add repositories for each extension we want to install.
For consistency, can we either use either artefact or artifact? 

Also, jut another suggestion: 

````
Each extension is distributed via it's own OCI artefact. Therefore, you need to add repositories for each extension that needs to be installed. 
````

2024-09-23 09:14 UTC, ranjinimn commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +3. On the *Repositories page* click `Create` button.
```suggestion
3. On the *Repositories page*, click `Create`.
```

2024-09-23 09:14 UTC, ranjinimn commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +4. In the form, specify the repository name and OCI artefact URL and click `Create`
```suggestion
4. In the form, specify the repository name and OCI artefact URL, and click `Create`
```

2024-09-23 09:14 UTC, ranjinimn commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +1. Click *Extensions* in the *Configuration* section of the navigation sidebar.
For numbering, instead of manual numbering, replace "1." with just "." "2." with ".", etc,. It will automatically provide the number. 
For example: 

````
. Click *Extensions* in the *Configuration* section of the navigation sidebar.
````

2024-09-23 09:14 UTC, ranjinimn commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +5. The extension repository is added to the list and showing the `Active` state.
Is there any action for the user here? Apart from seeing the status? 

```suggestion
. You can see that the extension repository is added to the list and is in `Active` state.
```

2024-09-23 09:14 UTC, ranjinimn commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +4. In the form, specify the repository name and OCI artefact URL and click `Create`
```suggestion
4. In the form, specify the repository name and OCI artefact URL and click `Create`.
```

2024-09-23 09:14 UTC, ranjinimn commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +Once the extension is installed Rancher UI will prompt to reload the page as described in the `https://ranchermanager.docs.rancher.com/integrations-in-rancher/rancher-extensions#installing-extensions
```suggestion
Once the extension is installed Rancher UI prompts to reload the page as described in the `https://ranchermanager.docs.rancher.com/integrations-in-rancher/rancher-extensions#installing-extensions[Installing Extensions Rancher documentation page]`.
```

2024-09-24 13:31 UTC, jtomasek commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +5. The extension repository is added to the list and showing the `Active` state.
No subsequent action here.

2024-09-24 13:35 UTC, jtomasek commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +2. On the Extensions page click the three dot menu at the top right and select *Manage Repositories*
Done

2024-09-24 13:35 UTC, jtomasek commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +Each extension is distributed via it's own OCI artefact. Therefore it is required to add repositories for each extension we want to install.
Done

2024-09-24 13:36 UTC, jtomasek commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +3. On the *Repositories page* click `Create` button.
Done

2024-09-24 13:36 UTC, jtomasek commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +4. In the form, specify the repository name and OCI artefact URL and click `Create`
Done

2024-09-24 13:36 UTC, jtomasek commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +1. Click *Extensions* in the *Configuration* section of the navigation sidebar.
Done

2024-09-24 13:36 UTC, jtomasek commented on asciidoc/components/rancher-dashboard-extensions.adoc
> +4. In the form, specify the repository name and OCI artefact URL and click `Create`
Done

2024-09-24 13:38 UTC, jtomasek commented
Thanks for your review @ranjinimn! I've updated the PR with your suggestions.

2024-09-24 19:53 UTC, jdob commented
While you're in here, can you look at the installation instructions for the plugin operator and see if we can pin them to versions? I'm a bit uncomfortable leaving them version-less. Here are the lines I'm talking about:

```
helm upgrade --create-namespace -n cattle-ui-plugin-system \
  --install ui-plugin-operator rancher-charts/ui-plugin-operator
helm upgrade --create-namespace -n cattle-ui-plugin-system \
  --install ui-plugin-operator-crd rancher-charts/ui-plugin-operator-crd
```

2024-09-24 19:53 UTC, jdob requested changes
Let me know if there's a reason we don't pin the ui-plugin-operator to a specific version and I'll remove the request changes flag.

2024-09-26 16:21 UTC, jdob approved these changes

2024-09-27 06:40 UTC, merged