init for updating docs to latest versions for 3.1 release
suse-edge/suse-edge.github.io pull request #376
Opened 2024-09-16 13:49 UTC by dprodanov4

Update docs and examples to our latest versions for 3.1 release.

2024-09-20 08:19 UTC, hardys commented on asciidoc/edge-book/releasenotes.adoc
> += Release 3.1
Given that we're starting a new branch for 3.1 docs we should call this `3.1.0`, mark the Availability date TBC, and remove all other z-streams (since there will only be one 3.1.0 until the first z-stream)

2024-09-20 08:20 UTC, hardys commented
Other than the release notes issue this looks good, thanks for working on it!

2024-09-24 14:44 UTC, hardys commented on asciidoc/edge-book/releasenotes.adoc
> +SUSE Edge 3.1.0 is a tightly integrated and comprehensively validated end-to-end solution for addressing the unique challenges of the deployment of infrastructure and cloud-native applications at the
Lets just make this `3.1` similar to the previous `3.0`

2024-09-24 14:44 UTC, hardys commented on asciidoc/edge-book/releasenotes.adoc
> +NOTE: SUSE Adaptive Telco Infrastructure Platform (ATIP) is a derivative (or downstream product) of SUSE Edge, with additional optimizations and components that enable the platform to address the req
Same here lets make this `3.1`

2024-09-24 14:46 UTC, hardys commented on asciidoc/edge-book/releasenotes.adoc
> +Summary: TBC.
Lets align with something similar to the 3.0.0 Summary e.g `SUSE Edge 3.1.0 is the first release in the SUSE Edge 3.1 release stream.`

2024-09-24 14:46 UTC, hardys commented on asciidoc/edge-book/releasenotes.adoc
> +| SLE Micro | 6 (latest) | N/A | https://www.suse.com/download/sle-micro/[SLE Micro Download Page] +
This should be `6.0`

2024-09-24 14:49 UTC, hardys commented on asciidoc/edge-book/releasenotes.adoc
> +| NeuVector| 5.3.0 | 104.0.0+up2.7.7 | registry.suse.com/rancher/mirrored-neuvector-controller:5.3.0 +
This should be `5.3.4` and `104.0.1+up2.7.9` ref https://github.com/rancher/charts/blob/release-v2.9/charts/neuvector/104.0.1%2Bup2.7.9/Chart.yaml I think

2024-09-24 14:50 UTC, hardys commented on asciidoc/edge-book/releasenotes.adoc
> +registry.suse.com/rancher/elemental-operator-crds-chart:1.6.4 +
This is now available in https://github.com/rancher/charts/blob/release-v2.9/charts/elemental/104.2.0%2Bup1.6.4/Chart.yaml - although in 3.0 we just referenced the OCI chart, so we could perhaps just remove the TODO then decide if we want to switch to the rancher/charts copy as a follow-up?

2024-09-24 14:51 UTC, hardys requested changes
A few minor comments but overall looks good, thanks!

We also need to do a batch update from `registry.suse.com/edge` to `registry.suse.com/edge/3.1` but that can potentially be done in a follow-up PR

2024-09-24 16:30 UTC, dprodanov4 commented
Yes, I left the batch update of the OBS to IBS out of this one on purpose so we can track it easier in a separate PR. Will address the other comments now. Thank you for the review

2024-09-24 20:12 UTC, jdob commented on asciidoc/edge-book/version-matrix.adoc
> +| Longhorn | 1.7.1 | 103.3.0 // TODO: update to correct chart version once rancher-charts/longhorn releases it
It'll be `104.2.0+up1.7.1`

https://github.com/rancher/charts/tree/dev-v2.9/charts/longhorn/104.2.0%2Bup1.7.1

2024-09-25 07:14 UTC, atanasdinov commented on asciidoc/components/longhorn.adoc
> +podman run --rm --privileged -it -v $CONFIG_DIR:/eib registry.suse.com/edge/edge-image-builder:1.1 build --definition-file $CONFIG_DIR/iso-definition.yaml
I'm not sure if the final URL wouldn't also contain `/3.1` but EIB's tag will be `1.1.0`. Please adjust all other references.
```suggestion
podman run --rm --privileged -it -v $CONFIG_DIR:/eib registry.suse.com/edge/edge-image-builder:1.1.0 build --definition-file $CONFIG_DIR/iso-definition.yaml
```

2024-09-25 11:12 UTC, hardys approved these changes

2024-09-25 12:27 UTC, merged