Initial SUSE Multilinux Manager chapter
suse-edge/suse-edge.github.io pull request #462
Opened 2024-10-10 15:12 UTC by joesusecom

This is the draft for the new SUMA chapter. Still work in progress.

2024-10-10 16:50 UTC, hardys commented on asciidoc/components/suse-multilinux-manager.adoc
> +TBD: Do we want to give customers options (Elemental all-in, direct registration against SCC), or is SUSE Manager the only fully supported (and documented) option (in SUSE Edge 3.1)?
We already document SCC registration so I think it makes sense to describe SUSE Manager as an optional alternative?

2024-10-10 16:51 UTC, hardys commented on asciidoc/components/suse-multilinux-manager.adoc
> +* Your registration code for SLE Micro 5.5
Should be 6.0

2024-10-10 16:52 UTC, hardys commented on asciidoc/components/suse-multilinux-manager.adoc
> +podman pull registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile-sp6/suse/edge-image-builder:1.1.0.rc2
Should be `registry.suse.com/edge/3.1/edge-image-builder:1.1.0`

2024-10-10 16:52 UTC, hardys commented on asciidoc/components/suse-multilinux-manager.adoc
> +SL-Micro.x86_64-6.0-Default-SelfInstall-GM.install.iso to the "base-images" directoy and name it "slemicro.iso".
Should be the new GM2 image

2024-10-10 16:53 UTC, hardys commented on asciidoc/components/suse-multilinux-manager.adoc
> +podman run --rm -it --privileged -v ./:/eib registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile-sp6/suse/edge-image-builder:1.1.0.rc2 build --definition-file iso-definition.yaml
Same as above should be the registry.suse.com version

2024-10-11 08:22 UTC, ipetrov117 commented on asciidoc/components/suse-multilinux-manager.adoc
> +As "Child Channel", select the "include recomended" slider for the hardware architecture your activation key is used for. This will add the "SUSE-Manager-Tools-For-SL-Micro-6.0" channel.
```suggestion
As "Child Channel", select the "include recommended" slider for the hardware architecture your activation key is used for. This will add the "SUSE-Manager-Tools-For-SL-Micro-6.0" channel.
```

2024-11-21 14:13 UTC, agracey commented on asciidoc/components/suse-multilinux-manager.adoc
> +== SUSE Manager
You'll also need to add the front-matter with an anchor then link to it from edge.adoc

2025-01-17 13:14 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +TBD: Do we want to give customers options (Elemental all-in, direct registration against SCC), or is SUSE Manager the only fully supported (and documented) option (in SUSE Edge 3.1)?
For now, I'll just not mention the other alternatives here. But we might need an intro snippet somewhere in the docs to list all the available OS patching options and explain which is best when.

2025-01-17 13:17 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +* Your registration code for SLE Micro 5.5
Correct. I still need to verify which code to use when the Edge Suite was purchased.

2025-01-17 13:49 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +podman pull registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile-sp6/suse/edge-image-builder:1.1.0.rc2
Fixed, using the variables like in the EIB Quick Start.

2025-01-17 14:57 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +SL-Micro.x86_64-6.0-Default-SelfInstall-GM.install.iso to the "base-images" directoy and name it "slemicro.iso".
Done.

2025-01-17 14:58 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +podman run --rm -it --privileged -v ./:/eib registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile-sp6/suse/edge-image-builder:1.1.0.rc2 build --definition-file iso-definition.yaml
Done.

2025-01-17 14:59 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +As "Child Channel", select the "include recomended" slider for the hardware architecture your activation key is used for. This will add the "SUSE-Manager-Tools-For-SL-Micro-6.0" channel.
Fixed.

2025-01-17 15:18 UTC, joesusecom commented
I think this is now almost ready for a first merge.

2025-01-17 17:44 UTC, hardys commented on asciidoc/components/suse-multilinux-manager.adoc
> +== SUSE Multi-Linux Manager: Keeping SUSE Linux Micro up to date
For this to show up correctly in the side menu we need to adjust like:

```
[#components-suma]
= SUSE Multi-Linux Manager
```

Then make corresponding adjustments to the following sections - see [my branch](https://github.com/hardys/suse-edge.github.io/commit/ca007d6288fee27999ff4ade11f6afcbf02b3cc7) for an example, and also the required addition to `edge-book/edge.adoc`

2025-01-17 17:44 UTC, hardys commented on asciidoc/components/suse-multilinux-manager.adoc
> +For a minimal lab setup, we can actually use the same virtual machine SUSE Multi-Linux Manager Server is running on. Please make sure that you have enough disk space in the virtual machine! This is n
We should use an internal reference e.g `<<id-prerequisites-2>>` (again see my branch linked above)

2025-01-17 17:45 UTC, hardys commented on asciidoc/components/suse-multilinux-manager.adoc
> +podman pull registry.suse.com/edge/{version-edge-registry}/edge-image-builder:{version-eib}
Note your branch is outdated, so will need a rebase for it to build with these attribute references.

2025-01-17 17:46 UTC, hardys requested changes
Overall looks good but a few changes needed as mentioned - also see https://github.com/hardys/suse-edge.github.io/commit/ca007d6288fee27999ff4ade11f6afcbf02b3cc7

2025-01-20 09:59 UTC, atrendafilov commented
LGTM! Once @hardy’s comments are addressed, this should be good to go.

2025-01-20 10:21 UTC, rdoxenham commented on asciidoc/components/suse-multilinux-manager.adoc
> +You will also need an additional block device to store the SUSE Multi-Linux Manager database and all RPM packages and files SUSE Multi-Linux Manager needs to operate. With your VM management tool, cr
Might I suggest that we move the block storage requirements to the list above so we're exhaustive in the list rather than adding this sentence afterwards?

2025-01-20 10:21 UTC, rdoxenham commented on asciidoc/components/suse-multilinux-manager.adoc
> +You need to set up the network so that your edge nodes can later access SUSE Multi-Linux Manager Server with a fully qualified host name!
```suggestion
You need to set up the network so that your edge nodes can later access SUSE Multi-Linux Manager Server with a fully qualified domain name (FQDN).
```

2025-01-20 10:23 UTC, rdoxenham commented on asciidoc/components/suse-multilinux-manager.adoc
> +In this quickstart we're using the "self-install" flavor of the SUSE Linux Micro image. That image can later be written to a physical USB thumb drive that you can use to install on physical servers.
```suggestion
In this quickstart we're using the "self-install" flavor of the SUSE Linux Micro image. That image can later be written to a physical USB thumb drive that you can use to install on physical servers. If your server has the option of remote attachment of installation ISOs via a BMC (Baseboard Management Controller), you can also use that approach. Finally that image can also be used with most virtualization tools.
```

2025-01-20 10:24 UTC, rdoxenham commented on asciidoc/components/suse-multilinux-manager.adoc
> +`SL-Micro.x86_64-6.0-Default-SelfInstall-GM2.install.iso` to the `base-images` directoy and name it "slemicro.iso".
You don't actually need to rename it. I think this is an unnecessary step and perhaps adds confusion. I'd suggest we just use the full name in the configuration file.

2025-01-20 10:25 UTC, rdoxenham commented on asciidoc/components/suse-multilinux-manager.adoc
> +Edge Image Builder can also configure the network, automatically install Kubernetes on the node, and even deploy applications via helm charts. See [here] for more comprehensive examples.
Where is [here]? We should update this link.

2025-01-20 10:25 UTC, rdoxenham commented on asciidoc/components/suse-multilinux-manager.adoc
> +In this example, the root password would be "root". See https://documentation.suse.com/suse-edge/3.2/html/edge/quickstart-eib.html#id-configuring-os-users[here] for creating password hashes for the s
We should templatise the Edge version here too.

2025-01-20 10:25 UTC, rdoxenham commented on asciidoc/components/suse-multilinux-manager.adoc
> +We use the option `noGPGCheck: true` because we aren't going to provide a GPG key to check RPM packages. See [here] for a more secure setup that we recommend for production use.
Another [here] to update

2025-01-20 10:27 UTC, rdoxenham commented on asciidoc/components/suse-multilinux-manager.adoc
> +You need to rename it to `RHN-ORG-TRUSTED-SSL-CERT.crt`. Edge Image Builder will make sure that the certificate is installed and activated on the edge node during installation.
Suggest we add a "WARN" block for this, as if the user doesn't have the `.crt` extension, EIB will ignore it, and nodes will fail to register to systems with self-signed certificates.

2025-01-20 13:12 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +You will also need an additional block device to store the SUSE Multi-Linux Manager database and all RPM packages and files SUSE Multi-Linux Manager needs to operate. With your VM management tool, cr
Done. Also added a snippet for using the mgr-storage-server command for actually configuring the storage for Multi-Linux Manager.

2025-01-20 13:16 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +You need to set up the network so that your edge nodes can later access SUSE Multi-Linux Manager Server with a fully qualified host name!
Done.

2025-01-20 13:17 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +In this quickstart we're using the "self-install" flavor of the SUSE Linux Micro image. That image can later be written to a physical USB thumb drive that you can use to install on physical servers.
Done.

2025-01-20 13:23 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +    host: ${fully qualified hostname of your SUSE Multi-Linux Manager Server}
So, I've double-checked, and the correct term is indeed "hostname" (once it contains the actual host's unique name, not just the domain/subdomain parts). The FQDN is just the domain part of it. So, where it made sense, I've elaborated on this, mentioning the "hostname" needs a FQDN part.

2025-01-20 13:26 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +In this example, the root password would be "root". See https://documentation.suse.com/suse-edge/3.2/html/edge/quickstart-eib.html#id-configuring-os-users[here] for creating password hashes for the s
Done.

2025-01-20 13:28 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +curl http://${HOSTNAME_OF_SUSE_MANAGER}/pub/repositories/slmicro/6/0/bootstrap/x86_64/venv-salt-minion-3006.0-1.1.x64_64.rpm
Done.

2025-01-20 13:31 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +You need to rename it to `RHN-ORG-TRUSTED-SSL-CERT.crt`. Edge Image Builder will make sure that the certificate is installed and activated on the edge node during installation.
Done.

2025-01-24 15:42 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +`SL-Micro.x86_64-6.0-Default-SelfInstall-GM2.install.iso` to the `base-images` directoy and name it "slemicro.iso".
I've kept the rename step for now. It has the benefit of not having to always touch the config when you download a new version. At least when doing rapid iterations (and not using templated YAML files), this, IMHO, makes sense.

2025-01-24 15:45 UTC, joesusecom commented on asciidoc/components/suse-multilinux-manager.adoc
> +We use the option `noGPGCheck: true` because we aren't going to provide a GPG key to check RPM packages. See [here] for a more secure setup that we recommend for production use.
Done.

2025-01-27 11:52 UTC, hardys commented
I pushed https://github.com/suse-edge/suse-edge.github.io/pull/558 which resolves the rebase issues here, and splits the content into component/quickstart pages - @joesusecom PTAL and see if you're happy to proceed with that branch, thanks!

2025-01-31 10:50 UTC, hardys commented
This was merged via #558

2025-01-31 10:50 UTC, closed without merging