Adding a Tips and Tricks section to Edge Book and adding the first page for EIB
suse-edge/suse-edge.github.io pull request #502
Opened 2024-11-27 17:51 UTC by Gagrio

Adding a Tips and Tricks section to Edge Book and adding the first page for EIB

2024-11-27 17:53 UTC, Gagrio commented
@e-minguez new PR here

2024-11-28 07:02 UTC, atanasdinov commented on asciidoc/tricks/eib.adoc
> +Example:
I think this example should be unified with the previous one in order to reduce distraction.

2024-11-28 07:08 UTC, atanasdinov commented on asciidoc/tricks/eib.adoc
> +- When creating an image for a multi node kubernetes cluster you need to have a way to declare which machine gets which hostname and if it's a server or agent. While the server/agent configuration is
```suggestion
- Edge Image Builder relies on the hostnames of the different nodes to determine their Kubernetes type (`server` or `agent`). While this configuration is managed in the definition file, for the general networking setup of the machines we can utilize either DHCP or the <<components-nmc>> component. 
```

2024-11-28 07:10 UTC, atanasdinov commented on asciidoc/tricks/eib.adoc
> +node1.suse.com.yaml contents:
Isn't it confusing to the user if we just copy-paste an example without any additional information? I feel like linking to the networking component should be more than enough to convey that the user has to do some more reading to come up with this and we already have a good example of tying it into EIB there.

2024-11-28 10:15 UTC, Gagrio commented on asciidoc/tricks/eib.adoc
> +  You will need to adjust the resources of the podman machine, either by using Podman Desktop (settings cogwheel -> podman machine edit icon) or directly  via the `podman-machine-set` https://docs.po
yeah it's here on v5.3.1:

![Screenshot 2024-11-28 at 11 12 52](https://github.com/user-attachments/assets/5403309b-be9c-463b-93b9-ea0d59f67ca1)

2024-11-28 10:15 UTC, Gagrio commented on asciidoc/tricks/eib.adoc
> +- If you are in a non-Linux OS, then you are running podman via a podman machine. This machine is low on resources on it's default settings and can cause Edge Image Builder to hung for resource inten
will do, thanks!

2024-11-28 10:16 UTC, Gagrio commented on asciidoc/tricks/eib.adoc
> +- To avoid any complications, the image architecture being built must match the one on the system running the Edge Image Builder container, for example if you are using an Apple Silicon MacBook, then
ack, rewording and cleaning up

2024-11-28 10:18 UTC, Gagrio commented on asciidoc/tricks/eib.adoc
> +- You can't create an image for a multi node kubernetes cluster without setting up an `kubernetes.network.apiVIP` parameter (even better add an `kubernetes.network.apiHost` parameter to the setup as
I like this approach, thanks for suggesting it, I will reword the negative approach into positive.

2024-11-28 10:18 UTC, Gagrio commented on asciidoc/tricks/eib.adoc
> +    apiHost: 192.168.64.11
alright, on it

2024-11-28 10:19 UTC, Gagrio commented on asciidoc/tricks/eib.adoc
> +Example:
ok I will add one example in the end to include all of the above

2024-11-28 10:19 UTC, Gagrio commented on asciidoc/tricks/eib.adoc
> +- When creating an image for a multi node kubernetes cluster you need to have a way to declare which machine gets which hostname and if it's a server or agent. While the server/agent configuration is
thank you

2024-11-28 10:20 UTC, Gagrio commented on asciidoc/tricks/eib.adoc
> +node1.suse.com.yaml contents:
ack, thanks

2024-11-28 13:49 UTC, Gagrio commented
reworked the document and added a link from [EIB component page](https://documentation.suse.com/suse-edge/3.1/html/edge/components-eib.html) to it.

2024-12-12 11:43 UTC, rdoxenham commented on asciidoc/tips/eib.adoc
> +- If you are in a non-Linux environment, then you are running `Podman` via a virtual machine. This machine is low on resources on its default settings and can cause `Edge Image Builder` to require un
```suggestion
- If you are in a non-Linux environment and following these instructions to build an image, then you are likely running `Podman` via a virtual machine. By default, this virtual machine will be configured to have a small amount of system resources allocated to it and can cause instability for `Edge Image Builder` during resource intensive operations, such as the RPM resolution process. You will need to adjust the resources of the podman machine, either by using Podman Desktop (settings cogwheel -> podman machine edit icon) or directly  via the `podman-machine-set` https://docs.podman.io/en/stable/markdown/podman-machine-set.1.html[command]
```

2024-12-12 11:46 UTC, rdoxenham requested changes
Thanks for the hard work here, @Gagrio! Just a few suggestions, but otherwise I appreciate you taking the time.

2024-12-12 11:46 UTC, rdoxenham commented on asciidoc/tips/eib.adoc
> +- At this point in time, the `Edge Image Builder` is not able to build images in a cross architecture setup, i.e. you have to run it on:
```suggestion
- At this point in time, `Edge Image Builder` is not able to build images in a cross architecture setup, i.e. the desired output architecture needs to match the machine in which you're building on:
```

2024-12-12 13:25 UTC, atanasdinov commented on asciidoc/components/edge-image-builder.adoc
> +link:../tips/eib.adoc[Read more EIB tips here]
I think this isn't the best place as the brief description above is only talking about what EIB is on very high level. Newcomers need to get familiar with all of the content below in order to make any sense of it.

I'd suggest to move this below at the end of the "Getting started" section with something similar to "Once you are familiar with this tool, please find some more useful information on our <link>[Tips and tricks] page.".

2024-12-12 13:46 UTC, atanasdinov commented on asciidoc/tips/eib.adoc
> +.Simple example of image creation for a multi server node RKE2 cluster with Rancher Prime:
I appreciate we're trying to provide examples for the users, but everything below is without context. Perhaps it'd make sense to have a brief explanation about what definition files are, what they entail and provide, and then have some sort of well formatted "Examples" section where we cover:
- single node k3s cluster
- multi node RKE2 cluster
- basic RAW image with some kernel args
- basic ISO image with some OS configs

All of those containing valid values for the different sections and versions matching the latest Edge release e.g. in the example below we have mismatching Rancher and RKE2 release versions and invalid `apiVIP` value.

2024-12-12 13:46 UTC, atanasdinov commented on asciidoc/tips/eib.adoc
> +**network files:**
I still believe these don't bring in any value as a standalone files without explanation. If we follow the suggestion above, we could add a "Note" or "Important" label to clarify that network configuration is required for the multi-node RKE2 example with link to the respective guide.

2024-12-17 12:24 UTC, Gagrio commented on asciidoc/tips/eib.adoc
> +- At this point in time, the `Edge Image Builder` is not able to build images in a cross architecture setup, i.e. you have to run it on:
Thank you!

2024-12-17 12:41 UTC, Gagrio commented on asciidoc/components/edge-image-builder.adoc
> +link:../tips/eib.adoc[Read more EIB tips here]
ack

2025-01-02 13:11 UTC, Gagrio commented on asciidoc/tips/eib.adoc
> +- `Edge Image Builder` relies on the hostnames of the different nodes to determine their Kubernetes type (`server` or `agent`). While this configuration is managed in the definition file, for the gen
Done

2025-01-09 08:06 UTC, atanasdinov approved these changes

2025-01-10 15:52 UTC, merged