change v1alpha1 from capi controlplane
suse-edge/suse-edge.github.io pull request #504
Opened 2024-12-11 14:16 UTC by alknopfler

- Change to move from v1alpha1 to v1beta1 in rke2controlplane 
- version in spec out of the agentConfig

2024-12-11 14:17 UTC, alknopfler commented
Also tested in the ATIP examples:
https://github.com/suse-edge/atip/pull/19

2024-12-11 14:33 UTC, alknopfler commented
> Thanks! Could it be that you missed a couple of instances?
> 
> ```
> > git remote -v
> origin	git@github.com:alknopfler/suse-edge.github.io.git (fetch)
> origin	git@github.com:alknopfler/suse-edge.github.io.git (push)
> > ack "controlplane.cluster.x-k8s.io/v1alpha1" asciidoc
> 
> asciidoc/components/rke2.adoc
> 54:apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
> 
> asciidoc/product/atip-automated-provision.adoc
> 680:    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
> 713:apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
> 952:    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
> 990:apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
> 1407:apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
> 1631:apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
> 1752:apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
> 
> asciidoc/product/atip-lifecycle.adoc
> 65:apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
> 
> asciidoc/quickstart/metal3.adoc
> 485:    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
> 504:apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
> ```

This is basically my PR

2024-12-11 14:34 UTC, fsundermeyer commented
Just noticed it after hitting "Comment". Sorry, was on the wrong branch ;-(

2024-12-11 14:35 UTC, fsundermeyer approved these changes
LGTM

2024-12-12 15:35 UTC, alknopfler commented on asciidoc/quickstart/metal3.adoc
> +  version: v1.30.5+rke2r1
sure!

2024-12-12 15:36 UTC, alknopfler commented on asciidoc/quickstart/metal3.adoc
> +  version: v1.30.5+rke2r1
changed

2024-12-13 12:08 UTC, alknopfler commented
@hardys I've also added the changes we commented this week:
- identifier: mac-address for the static dhcp-less environment
- remove the OS version from the EIB output image name to make it easy to be updated every release

2024-12-13 12:56 UTC, fsundermeyer requested changes

2024-12-13 12:56 UTC, fsundermeyer commented on asciidoc/product/atip-management-cluster.adoc
> +The `mgmt-cluster.yaml` file must be modified to include the `embeddedArtifactRegistry` section with the `images` field set to all container images to be included into the EIB output image. The `imag
The two sentences include duplicated information. I suggest something like the following:

```suggestion
The `mgmt-cluster.yaml` file must be modified to include the `embeddedArtifactRegistry` section.
In this section the `images` field must contain the list of all container images to be included in the output image.
```

2024-12-13 12:56 UTC, fsundermeyer commented on asciidoc/product/atip-management-cluster.adoc
> +The following is only an example of the `mgmt-cluster.yaml` file with the `embeddedArtifactRegistry` section included. Please take care of the image version depending on the components needed.
Not sure I fully understand the second sentence. How about;

```suggestion
The following is an example of the `mgmt-cluster.yaml` file with the `embeddedArtifactRegistry` section included.
Make sure to the listed images contain the component versions you need.
```

2024-12-13 13:08 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +The `mgmt-cluster.yaml` file must be modified to include the `embeddedArtifactRegistry` section with the `images` field set to all container images to be included into the EIB output image. The `imag
makes sense! changed! Thanks

2024-12-13 13:09 UTC, alknopfler commented on asciidoc/product/atip-management-cluster.adoc
> +The following is only an example of the `mgmt-cluster.yaml` file with the `embeddedArtifactRegistry` section included. Please take care of the image version depending on the components needed.
much better! Thanks

2024-12-13 13:12 UTC, fsundermeyer commented on asciidoc/product/atip-management-cluster.adoc
> +The following is only an example of the `mgmt-cluster.yaml` file with the `embeddedArtifactRegistry` section included. Please take care of the image version depending on the components needed.
Actually I added a superfluous  "to". Should be: Make sure the listed images contain the component versions you need.

Sorry.

2024-12-16 09:54 UTC, hardys commented on asciidoc/quickstart/metal3.adoc
> +  version: v1.30.5+rke2r1
I don't think the attribute replacement is working - we need to add `subs="attributes"` to the yaml blocks where the attribute is referenced e.g:

```
git diff
diff --git a/asciidoc/quickstart/metal3.adoc b/asciidoc/quickstart/metal3.adoc
index c5aea00..505737e 100644
--- a/asciidoc/quickstart/metal3.adoc
+++ b/asciidoc/quickstart/metal3.adoc
@@ -466,7 +466,7 @@ To deploy the controlplane we define a yaml manifest similar to the one below, w
 Note for simplicity this example assumes a single-node controlplane, where the BareMetalHost is configured with an IP of `192.168.125.200` - for more
 advanced multi-node examples please see the <<atip-automated-provisioning, ATIP documentation>>
 
-[,yaml]
+[,yaml,subs="attributes"]
 ----
 apiVersion: cluster.x-k8s.io/v1beta1
 kind: Cluster
@@ -602,7 +602,7 @@ Similar to the controlplane we define a yaml manifest, which contains the follow
 * Metal3MachineTemplate defines the OS Image to be applied to the BareMetalHost resources, and the hostSelector defines which BareMetalHosts to consume
 * Metal3DataTemplate defines additional metaData to be passed to the BareMetalHost (note networkData is not currently supported in the Edge solution)
 
-[,yaml]
+[,yaml,subs="attributes"]
 ----
 apiVersion: cluster.x-k8s.io/v1beta1
 kind: MachineDeployment
```

2024-12-17 09:27 UTC, alknopfler commented on asciidoc/quickstart/metal3.adoc
> +  version: v1.30.5+rke2r1
you're right! good catch! I've changed

2024-12-17 11:20 UTC, hardys approved these changes

2024-12-17 13:11 UTC, fsundermeyer approved these changes
Thanks for making teh changes

2024-12-17 13:12 UTC, merged