add mgmt cluster docs for atip
suse-edge/suse-edge.github.io pull request #65
Opened 2023-07-18 08:32 UTC by alknopfler

Add doc for ATIP section:
- Mgmt cluster installation
- Edge site installation
- Feature configuration (each feature should be standalone containing all the step to enable it)

2023-07-19 10:12 UTC, hardys reviewed
Looks great, couple of small comments added

2023-07-19 10:45 UTC, alknopfler commented on docs/product/atip/edge-site.md
> +
Yes, you're right!! The first time I thought exactly the same. I think this is something to share with the Rancher's team

2023-07-19 10:45 UTC, alknopfler commented on docs/product/atip/management-cluster.md
> +4. Create the directory structure as mentioned in Chapter 8, Configuring with Ignition or Chapter 9, Configuring with Combustion, depending on the configuration tool used:
ohh good catch!! I will change it adding a note for more information.

2023-07-21 15:27 UTC, e-minguez commented on docs/product/atip/requirements.md
> +## Disable rebootmgr strategic
```suggestion
## Disable rebootmgr
```

2023-07-21 15:27 UTC, e-minguez commented on docs/product/atip/requirements.md
> +For telco workloads is really important to disable the rebootmgr strategic in order to avoid the reboot of the nodes in case of updates scheduled by the system.
```suggestion
For telco workloads is really important to disable rebootmgr in order to avoid the reboot of the nodes in case of updates scheduled by the system.
```

2023-07-21 15:28 UTC, e-minguez commented on docs/product/atip/requirements.md
> +You could verify the strategic status using the next command:
```suggestion
You could verify the strategy being used as:
```

2023-07-21 15:28 UTC, e-minguez commented on docs/product/atip/requirements.md
> +and you could disable it using the next command:
```suggestion
and you could disable it as:
```

2023-07-21 15:29 UTC, e-minguez commented on docs/product/atip/requirements.md
> +> For more information about rebootmgr, please check: https://github.com/SUSE/rebootmgr
It would be better if you put this first and add a brief explanation... otherwise users like myself that doesn't know what is will be wondering why I need to disable this if I don't even know what it does.

2023-07-21 15:34 UTC, e-minguez commented on docs/product/atip/management-cluster.md
> +The server used for the management cluster should be installed on VMs or bare metal. The management cluster can be installed on a single node, but it is recommended to have at least 3 nodes for HA.
```
This page explains how to install and configure the management cluster. The management cluster is the cluster that will be used to manage the edge clusters.
The server used for the management cluster should be installed on VMs or bare metal. The management cluster can be installed on a single node, but it is recommended to have at least 3 nodes for HA.
```

This paragraph is a little bit messy IMHO... I'd say:

* First explain what the management cluster is.. but in a more elaborated way, saying "it manages edge clusters" doesn't mean anything to me. Is it Kubernetes? Again, a little bit more explanation won't hurt.
* What does it mean it should be installed on VMs or bare metal? both scenarios will be supported? which are the advantages of going one route or another?
* Same for single node vs 3 nodes.

2023-07-21 15:34 UTC, e-minguez commented on docs/product/atip/management-cluster.md
> +- A minimum of 1GB of RAM per node available to be used by the management cluster
```
 available to be used by the management cluster
```

What does it mean? Do you need to take into account the memory available for the OS?

2023-07-21 15:35 UTC, e-minguez commented on docs/product/atip/management-cluster.md
> +- Accurate time synchronization between all nodes in the cluster
I guess you can clarify if you need NTP/Chronyd or PTP (and link to a guide on how to enable ntp/chronyd or ptp)

2023-07-21 15:35 UTC, e-minguez commented on docs/product/atip/management-cluster.md
> +- A minimum of 2 vCPUs per node available to be used by the management cluster
Same question than the one for the memory.

2023-07-21 15:36 UTC, e-minguez commented on docs/product/atip/management-cluster.md
> +SUSE Linux Enterprise Micro 5.4 is available on the AMD64 and Intel* 64 (x86_64), Arm* 64 and IBM* z System or LinuxONE (s390x) hardware architectures.
Those asterisks are intended? Also, do we support ATIP on s390x?

2023-07-21 15:39 UTC, e-minguez commented on docs/product/atip/management-cluster.md
> +3. Configure the config.yaml:
where is this file located?

2023-07-21 15:40 UTC, e-minguez commented on docs/product/atip/management-cluster.md
>  ##  Rancher Install
```suggestion
##  Rancher Manager Install
```

2023-07-21 15:41 UTC, e-minguez commented on docs/product/atip/management-cluster.md
> +There are three releases available to be added as a Helm repository for Rancher. In our case, we will use the `rancher-stable` because it's the release recommended for production environments, but yo
There is also rancher prime, which is the enterprise version https://ranchermanager.docs.rancher.com/getting-started/quick-start-guides/deploy-rancher-manager/prime

2023-07-21 15:42 UTC, e-minguez requested changes
Added some comments/suggestions

2023-07-21 15:43 UTC, e-minguez commented on docs/product/atip/edge-site.md
> +To do that we will use the next tabs on the left side:
?

2023-07-21 15:43 UTC, e-minguez commented on docs/product/atip/edge-site.md
> +
Doing it via the UI is ok, but I guess most customers will prefer creating the objects and applying them via kubectl.

2023-07-21 15:47 UTC, e-minguez commented on docs/product/atip/edge-site.md
> +Rancher offers the possibility to use extra registries to be used by the edge site. This is really useful in case you need to use some extra images which are not available in the default registries,
Sorry, but this confuses me. This is just to enable pulling images from a registry with authentication without giving users access to the user/password right?
I mean you can ALWAYS pull images from any container registry in the world... you just need to put the proper url like 'registry.opensuse.org/kubevirt/virt-operator:1.0.0' and you can always configure pull secrets to pull images that requires authentication https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ so to be honest I don't know if we need this section at all.

2023-07-21 15:48 UTC, e-minguez commented on docs/product/atip/edge-site.md
> +Rancher offers the possibility to use different CPU management policies to be used by the edge site.
This is not completely true :) RKE2 is.

2023-07-21 15:50 UTC, e-minguez commented on docs/product/atip/edge-site.md
> +
Same here, using the UI is ok, but the cli option is better.

2023-07-21 15:50 UTC, e-minguez commented on docs/product/atip/edge-site.md
Same here, using the UI is ok, but the cli option is better.

2023-07-24 09:02 UTC, alknopfler commented on docs/product/atip/management-cluster.md
> +SUSE Linux Enterprise Micro 5.4 is available on the AMD64 and Intel* 64 (x86_64), Arm* 64 and IBM* z System or LinuxONE (s390x) hardware architectures.
* -> typo thanks
In the official download page we've got that support for s390x
https://www.suse.com/download/sle-micro/

2023-07-24 09:10 UTC, alknopfler commented on docs/product/atip/edge-site.md
> +To do that we will use the next tabs on the left side:
: typo

2023-07-24 09:10 UTC, alknopfler commented on docs/product/atip/edge-site.md
> +
talked with Gary but let's keep as UI

2023-07-24 09:11 UTC, alknopfler commented on docs/product/atip/edge-site.md
> +Rancher offers the possibility to use extra registries to be used by the edge site. This is really useful in case you need to use some extra images which are not available in the default registries,
You could configure authorization for the extra custom registry. I will add a note for that point

2023-07-26 12:36 UTC, e-minguez approved these changes
It is ok to me but still I miss how to do it the cli way :) I'll open an issue to keep track of this.

2023-07-26 14:46 UTC, merged