flexran blogpost entry
suse-edge/suse-edge.github.io pull request #68
Opened 2023-07-27 07:32 UTC by alknopfler

2023-07-28 09:40 UTC, e-minguez reviewed
Added a few suggestions. PTAL.

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +With this cloud-native setup, you can simplify the installation and configuration of Intel® FlexRAN on the `Suse Edge ATIP` (Adaptive Telco Infrastructure Platform) stack, enabling you to focus on si
```suggestion
With this cloud-native setup, you can simplify the installation and configuration of Intel® FlexRAN on the `Suse Edge ATIP` (Adaptive Telco Infrastructure Platform) stack, enabling you to focus on site-specific vRAN customizations vRAN. Also, it demonstrates that telecom containerised applications like DU/CU can be run on RKE2 cluster on top of the SLE Micro RT OS taking advantage of the accelerator cards. In addition, we show that we are applying the full power and potential of the accelerator card and CPU.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +The architecture for this article is based on the following components:
```suggestion
The architecture is based on the following components:
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +- Edge Cluster 1: This cluster will be used to deploy the `FlexRan Timer Mode tests`. This cluster is based on the SLE Micro RT Operating System and the RKE2 kubernetes cluster (single node) on top o
```suggestion
- Edge Cluster 1: This cluster will be used to deploy the `FlexRan Timer Mode tests`. This cluster is based on a single-node RKE2 cluster on top of SLE Micro RT Operating System.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +- Edge Cluster 2: This cluster will be used to deploy the `FlexRan Xran Mode tests`. This cluster is based on the SLE Micro RT Operating System and the RKE2 kubernetes cluster (single node) on top of
```suggestion
- Edge Cluster 2: This cluster will be used to deploy the `FlexRan Xran Mode tests`. This cluster is based on a single-node RKE2 cluster on top of SLE Micro RT Operating System.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +- Rancher Management Cluster: This component will be used to manage the lifecycle of the RKE2 clusters deployed for the FlexRAN solution, as well as the monitoring platform based on Grafana and Prome
```suggestion
- Rancher Management Cluster: This component will be used to manage the lifecycle of the RKE2 clusters deployed for the FlexRAN solution, as well as the monitoring platform based on Grafana and Prometheus. This cluster is based on a single-node RKE2 cluster on top of SLE Micro Operating System.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +- CNI plugins: `Multus + Calico`
Which versions?

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +- Rancher release: `rancher-stable`
Which version?

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +- SRIOV upstream
Which version?

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +The FlexRan version used for this article is based on the following components:
```suggestion
The FlexRan deployment used for this article is based on the following components:
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +In our case, the Rancher management cluster will be used to manage the lifecycle of the RKE2 edge clusters deployed for the FlexRAN solution, as well as the monitoring platform based on Grafana and P
```suggestion
In this example, the Rancher management cluster will be used to manage the lifecycle of the RKE2 edge clusters deployed for the FlexRAN solution, as well as the monitoring platform based on Grafana and Prometheus.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +> For this article, we will assume the Operating System is already installed on the Management Server.
```suggestion
> The operating system installation steps have been omitted for the sake of brevity.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +Once you have the Operating System installed, you can proceed with the Rancher installation. For this article, we will install a RKE2 cluster and then, the Rancher Helm chart to install the Rancher m
```suggestion
The following steps show how to install RKE2:
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +if you want to install a especific version, you can use the following command (i.e. `v1.25.9+rke2r1`):
```suggestion
If you want to install a particular version(i.e. `v1.25.9+rke2r1`) the `INSTALL_RKE2_VERSION` variable can be used as:
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +`systemctl start rke2-server.service`
```suggestion
2. Enable and start the rke2-server service:

`systemctl enable --now rke2-server.service`
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +In case you want to run the RKE2 agent, you can follow the next steps:
A brief explanation here about why you would like to do this would be nice.

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +
```suggestion
2. Configure the config.yaml file located in `/etc/rancher/rke2/` with the following content:

```yaml
server: https://<server>:9345
token: <token from server node>
```

3. Enable and start the service:

`systemctl enable --now rke2-agent.service`
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +
I don't know why GitHub breaks my suggestion :(

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +Helm charts provide templating syntax for Kubernetes YAML manifest documents. With Helm, we can create configurable deployments instead of just using static files.
```suggestion
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +> This section covers the installation of Rancher on the management cluster nodes.
```suggestion
> This section covers the deployment of Rancher on the management cluster.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +> For more information about the installation, please refer to the documentation: https://ranchermanager.docs.rancher.com/v2.7/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster
```suggestion
> For more information about the Rancher manager installation, please refer to the documentation: https://ranchermanager.docs.rancher.com/v2.7/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +There are three releases available to be added as a Helm repository for Rancher. In our case, we will use the `rancher-stable` because it's the release recommended for production environments, but yo
```suggestion
There are three Rancher manager releases available to be added as a Helm repository for Rancher. In our case, we will use the `rancher-stable` because it's the release recommended for production environments, but you could use `rancher-latest` or `rancher-alpha` if you want. Also, there is a `rancher primer` release that is the enterprise version of Rancher.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +In our case we will use the Rancher-generated TLS certificate:
```suggestion
In our case we will use the Rancher-generated TLS certificate. This requires `cert-manager` to be deployed in the cluster as:
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +3. Install Rancher with Helm and your chosen certificate option
```suggestion
3. Install Rancher with Helm using the following command modifying the `<hostname>` and `<bootstrapPassword>` values to fit your environment:
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +
```suggestion
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +
```suggestion
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +This section is really important to optimize the performance of the real time kernel in the hardware, because some of this parameters could increase not limiting the performance of the real time kern
```suggestion
Pay special attention to the parameters suggested here as some of them could dramatically increase or decrease the performance of the tests being executed.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +For this article, we will assume the Operating System Micro RT is installed on the baremetal for edge clusters. The most important thing is to ensure you're using the `Real Time Kernel`. In our case,
```suggestion
For this example, we will assume the SLE Micro RT 5.4 operating system has been already installed on the baremetal host used to deploy the edge clusters.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +
```suggestion
To verify the kernel version, you can use the following command (pay attention to the `-rt` suffix):

```shell
$ uname -r
5.14.21-150400.15.11-rt
```

```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +> For more information about how to install the Operating System SLE Micro RT, see the next [link](https://suse-edge.github.io/docs/product/atip/management-cluster#os-install)
```suggestion
> For more information about how to install the SLE Micro RT operating system, see the next [link](https://suse-edge.github.io/docs/product/atip/management-cluster#os-install)
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +The first thing is to create a profile for the cpu cores we want to isolate. In this case, we will isolate the cores 1-30 and 33-62.
Why you want to isolate those cores?

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +The first thing is to create a profile for the cpu cores we want to isolate. In this case, we will isolate the cores 1-30 and 33-62.
Also CPU instead of cpu

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +
```suggestion
> The grub configuration will be generated in the next step.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +We need to modify grub option to configure the isolate cpu cores as well as another important parameters for the cpu usage.
```suggestion
We need to modify some grub options to be able to do the CPU isolation as well as another parameters for CPU performance on this scenario.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +Modify in /etc/default/grub the next line, to add the cpu cores to isolate. The next options are the most important to be customized with your current hardware:
```suggestion
Modify the `/etc/default/grub` file to add the CPU cores to isolate. The next options are the most important to be customized with this example hardware:
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +| skew_tick| 1 | This option allows the kernel to skew the timer interrupts across the isolated CPUs.                     |
```suggestion
| skew_tick| 1 | Allows the kernel to skew the timer interrupts across the isolated CPUs.                     |
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +| nohz| on | This option allows the kernel to run the timer tick on a single CPU when the system is idle.             |
```suggestion
| nohz| on | Allows the kernel to run the timer tick on a single CPU when the system is idle.             |
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +| hugepages | 40    | This is the number of hugepages defined before          |
`This option` doesn't add anything and makes the table unnecessary bigger.

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +| default_hugepagesz| 1G | This is the default value to get the huge pages |
```suggestion
| default_hugepagesz| 1G | This is the default value to enable huge pages |
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +
I miss a lot of information here about those parameters and why are they important. Maybe I don't have enough context/knowledge about this but I recommend you to add some links/references for folks to read more about this.

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +transactional-update grub.cfg
My recommendation is to make this much more clear. I don't know which line I'm supposed to change nor what was the previous content.

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +Set cpu core frequency to 2.6Ghz:
Why that particular number?

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +Set cpu uncore to fixed – maximum allowed. Disable c6 and c1e (only if enabled):
Same, no explanation here.

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +In our case, for simplicity and reducing the article size, we will install a new RKE2 Cluster from scratch importing it after that directly into Rancher.
```suggestion
In our case, for brevity we will install a new RKE2 Cluster from scratch importing it after that directly into Rancher.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +In our case we're using the next version: `v1.25.9+rke2r1`
```suggestion
In this scenario we use the `v1.25.9+rke2r1` version as:
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +```
I don't think this is the proper way. Yes we did it for the scripts but you should use the rke2 config file https://docs.rke2.io/install/configuration

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +systemctl daemon-reload; systemctl enable rke2-server; systemctl start rke2-server
```suggestion
systemctl daemon-reload && systemctl enable --now rke2-server
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +Let's see the pods to ensure calico and multus are running:
```suggestion
Make sure the calico and multus pods are running:
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +Let's see the pods to ensure calico and multus are running:
In fact, there are no multus pods AFAIK... what would be the best way to check if multus has been deployed?

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +The ACC100 accelerator card is a PCIe card that provides a hardware acceleration for the Forward Error Correction (FEC) algorithm. This card is used by the FlexRan library to accelerate the FEC algor
```suggestion
The ACC100 accelerator card is a PCIe card that provides hardware acceleration for the Forward Error Correction (FEC) algorithm. This card is used by the FlexRan library to improve the performance of the DU/CU components.
```
Remove the redundancy

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +1. Load igb_uio kernel module
```suggestion
1. Load the `igb_uio` kernel module
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +We will start configuring the Accelerator Card to load the ibg_uio and the vfio-pci module.
```suggestion
We will start configuring the Accelerator Card by loading the `ibg_uio` and the `vfio-pci` module.
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +> During the OS configuration section we have installed the igb driver, dpdk as well as the pf-bb-config tool [requirements](./2023-07-28-flexran.md#os-configuration-and-tunning)
```suggestion
> During the OS configuration section we have installed the `ibg` driver, `dpdk` as well as the `pf-bb-config` tool [requirements](./2023-07-28-flexran.md#os-configuration-and-tunning)
```

Always use format style for commands, packages and things like that.

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +2. Get interface information ACC100
```suggestion
2. Verify ACC100 has been enabled by the OS
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +
```suggestion
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +lspci | grep -i acc
```suggestion
$ /sbin/lspci | grep -i acc
```
You don't need to add /sbin to the path just to run a command, you can use the full path.

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +3. Bind the PF with igb_uio driver:
```suggestion
3. Bind the Physical Function (PF) to the `igb_uio` driver:
```

Hint: When you use a term such as PF, you should always put what it means the first time (Physical Function in this case IIRC).

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +4. Create 2 vfs from the PF and bind with vfio-pci driver:
Same for VFS

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +4. Create 2 vfs from the PF and bind with vfio-pci driver:
and bind _them_

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +5. Configure acc100 using the pf-bb-config tool:
use backticks to style the commands

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +The Physical Function (PF) Baseband Device (BBDEV) Configuration Application (pf_bb_config) provides a means to configure a baseband device at the host level. The program accesses the configuration s
same

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +> For more information about the pf-bb-config tool, please refer to the [documentation](https://github.com/intel/pf-bb-config)
same

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +Tue Jun  6 10:49:21 2023:INFO:ACC100 PF [0000:8a:00.0] configuration complete!
Add the $ prompt or a new line after the command that was typed by the user, otherwise is a little bit confusing.

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +6. Check the new VFs created which will be used by the FlexRan library:
```suggestion
6. Check the new VFs created are available and ready to be used by the FlexRan library:
```

2023-07-28 09:40 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +
I'm stopping here and will continue later.

2023-07-28 10:01 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +
because you forgot the ``` ???
but it's ok no worries

2023-07-28 10:28 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +Let's see the pods to ensure calico and multus are running:
yes there's multus pod: rke2-multus-ds-4zsqr  
no need another way to check this

2023-07-28 10:33 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +
I want to keep that info because it was something useful for the customer PoC so let's keep that info.

2023-07-28 10:40 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +The Physical Function (PF) Baseband Device (BBDEV) Configuration Application (pf_bb_config) provides a means to configure a baseband device at the host level. The program accesses the configuration s
what's same? the explanation of pf-bb-config is inside

2023-07-28 12:27 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +- CNI plugins: `Multus + Calico`
You closed this as resolved but still there is no multus/calico versions

2023-07-28 13:24 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +- CNI plugins: `Multus + Calico`
you're right. Updated with the version

2023-07-28 13:25 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +- Rancher release: `rancher-stable`
updated with the rancher version

2023-07-28 13:25 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +- SRIOV upstream
updated with the version

2023-07-28 13:26 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +In our case, the Rancher management cluster will be used to manage the lifecycle of the RKE2 edge clusters deployed for the FlexRAN solution, as well as the monitoring platform based on Grafana and P
not really difference between both

2023-07-28 13:27 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +In case you want to run the RKE2 agent, you can follow the next steps:
thanks. updated with the explanation

2023-07-28 13:27 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +Helm charts provide templating syntax for Kubernetes YAML manifest documents. With Helm, we can create configurable deployments instead of just using static files.
I'd like to keep that information

2023-07-28 13:29 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +The first thing is to create a profile for the cpu cores we want to isolate. In this case, we will isolate the cores 1-30 and 33-62.
changed to explain a little but it's part of the flexran reqs

2023-07-28 13:30 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +
I think is not neccesary

2023-07-28 13:31 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +
I think is part of the context of the blog post, but let add some links to the ATIP doc features

2023-07-28 13:33 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +transactional-update grub.cfg
I think it's clear because basically is to add the parameteres described before using the table

2023-07-28 13:33 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +1. Create the VF PCI addresses in the node:
```suggestion
1. Create the VFs
```

2023-07-28 13:36 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +> For more information about the pf-bb-config tool, please refer to the [documentation](https://github.com/intel/pf-bb-config)
sorry could you say me what's same?

2023-07-28 13:37 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +1. Create the VF PCI addresses in the node:
I prefer give the context about pci addr

2023-07-28 13:45 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +5. Configure acc100 using the pf-bb-config tool:
but...it has backsticks right?

2023-07-28 14:00 UTC, e-minguez reviewed
Added more comments. PTAL.

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +The SR-IOV Network Device Plugin is Kubernetes device plugin for discovering and advertising networking resources in the form of:
```suggestion
The SR-IOV network device plugin is a Kubernetes device plugin for discovering and advertising networking resources such as:
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +For this article, we will use the next references to deploy Intel FlexRan on the Suse ATIP Edge Cluster:
```suggestion
For this article, we will use the next references to deploy the Intel FlexRan reference implementation on top of the the ATIP edge cluster:
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +- You will also need to download the FlexRan-22.07 tarball from Intel to run the tests and mount the downloaded `tests` folder into the pre-defined containers because it's not included into the pre-d
```suggestion
- You will also need to download the FlexRan-22.07 tarball from Intel to run the tests and mount the downloaded `tests` folder into the pre-defined containers because it's not included into the pre-defined containers.

> In order to download those files, it is required to have access to the Intel website (you can ask your Intel representative).
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +  - FlexRAN-22.07-L1.tar.gz_part01
It would be nice if you can provide either sha256 sums or md5sums of those files just in case

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +- Container Entrypoint script (Just in case you need to change anything else like the MAC addresses for the VFs)
Can you show an example of this?

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +Before starting to deploy the FlexRan containers, let's review the next things:
```suggestion
Before deploying the FlexRan containers, let's review the next steps:
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +### Container Entrypoint
```suggestion
### Container entrypoint
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +- `export INTEL_COM_INTEL_CPULIST=$(cat /sys/fs/cgroup/cpuset/cpuset.cpus)` to get the cpu list of the host machine.
```suggestion
- `export INTEL_COM_INTEL_CPULIST=$(cat /sys/fs/cgroup/cpuset/cpuset.cpus)` to get the CPU list of the host machine.
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +- `PCIDEVICE_INTEL_COM_INTEL_FEC_5G=$(env|grep PCIDEVICE_INTEL_COM_INTEL_FEC_5G= |awk -F '=' '{print $2}')`  in order to select the right PCI device for the FEC ACC100 used for the 5G acceleration.
```suggestion
- `PCIDEVICE_INTEL_COM_INTEL_FEC_5G=$(env|grep PCIDEVICE_INTEL_COM_INTEL_FEC_5G= |awk -F '=' '{print $2}')`  in order to select the right PCI device for the FEC ACC100 card used for the 5G acceleration.
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +Then, we need to modify the rest of the block to remove the tests which are not covered in the version of the flexran container we are using.
```suggestion

Then, we need to remove (or comment with the hashtag `#` sign) the tests not covered by the flexran container version we are using (the test files are not present in the FlexRan tests suite used so the script will fail):
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +We are going to remove (or use # to comment the lines) the next blocks line inside the container entrypoint script:
```suggestion
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +The reason to comment that block is because the files are not present in the FlexRan tests suite into the container and the script will fail without any other substitutions.
```suggestion
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +As you can see the next resource will be required:
```suggestion
The next resources are required:
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +This will launch automatically the Timer Mode Tests which contains 83 tests for the FlexRan library. It could take up to 3 hours running all the tests. You can check the status of the tests in the lo
```suggestion
This will launch automatically the Timer Mode Tests which contains 83 tests for the FlexRan library. It could take up to 3 hours to complete the tests. The status of the tests can be found in the container logs:
```

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +As you can see the next resource will be required:
Same as before

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +```
I guess you can put the kubectl exec command here as well.

2023-07-28 14:00 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +Using `htop` we could see the CPU usage of the containers as well as the pinned cores for this workload:
```suggestion
Using `htop` we could observe the CPU usage of the containers as well as the pinned cores for this workload:
```

2023-07-28 14:05 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +The SR-IOV Network Device Plugin is Kubernetes device plugin for discovering and advertising networking resources in the form of:
changed

2023-07-28 14:09 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +  - FlexRAN-22.07-L1.tar.gz_part01
let me check it but I think is not available on the resource website

2023-07-28 14:12 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +- Container Entrypoint script (Just in case you need to change anything else like the MAC addresses for the VFs)
The docker entrypoint file is really really big (over 800 lines) because it contains all the tests substitutions blocks. I think is not something relevant because we've just only describe the 3 things we have to change and how we're changing that part. 
it's something I've been thinking a lot during the time I'm writing the blog post but I think the best option for us it's just describe the minimum changes to make it work.

2023-07-28 14:13 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +The Physical Function (PF) Baseband Device (BBDEV) Configuration Application (pf_bb_config) provides a means to configure a baseband device at the host level. The program accesses the configuration s
the backticks. See https://developers.google.com/style/code-in-text

2023-07-28 14:14 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +The /home/tmp_flexran will be the folder to be mounted into the containers on the next section.
I will change the first part backsticks, but I think makes more sense to explain that will be the mount point for the tests

2023-07-28 14:21 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +We are going to remove (or use # to comment the lines) the next blocks line inside the container entrypoint script:
I think it's the same than before, so changed that in the previous one

2023-07-28 14:24 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +Smaller storage is built in pod as Kubernetes resources, but the larger storage is mapped from the host.
Basically the tests folder size is up to 20Gb, so what I'm explaining here is that the storage resource requests is a small storage for the container, but the larger storage is mapped to the tests folder. 
let me change the last part of the sentece for clarity

2023-07-28 14:28 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +At the end of the tests, you should see the next output:
I accept this because we're showing the success result, but this is not only for success result. Even if you have some failures you will get the logs

2023-07-28 14:32 UTC, e-minguez commented on blog/2023-07-28-flexran.md
> +  - FlexRAN-22.07-L1.tar.gz_part01
but you can generate those, right?

2023-07-28 14:32 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +Using `htop` we could see the CPU usage of the containers as well as the pinned cores for this workload:
mostly it's the same meaning, right?  hehe

2023-07-28 14:37 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +> For more information about the pf-bb-config tool, please refer to the [documentation](https://github.com/intel/pf-bb-config)
ok.

Done in previous too

2023-07-28 14:40 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +  - FlexRAN-22.07-L1.tar.gz_part01
but why? what's the benefits of that if we're not providing the files?
I mean... I could but why?

2023-10-16 13:06 UTC, timirnich commented
Sending my comments so far as is, to unblock @alknopfler. I'll get back to reproducing things on my system asap and will continue in another review.

2023-10-16 13:08 UTC, timirnich requested changes
Sending my review comments thus far, probably more to come.

2023-10-16 14:04 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +title: Deploying FlexRan on Suse Edge ATIP
makes sense. Changed

2023-10-16 14:05 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +Intel® FlexRAN is a reference implementation for cloud enabled wireless access virtual network functions `VNFs`. It shows how to efficiently implement wireless access loads through flexible software
done

2023-10-16 14:06 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +This article focuses on using [Rancher](https://www.rancher.com/) to perform cluster life cycle management, cloud-native microservices life cycle management, contained application resource management
done

2023-10-16 14:10 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +> For more infomration about Suse ATIP, see the official [Suse Edge ATIP](https://deploy-preview-68--frolicking-rolypoly-9c0c48.netlify.app/docs/product/atip/introduction)
you're right! that was the preview doc

2023-10-16 14:12 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +token: <token from server node>
yes, there's a note before that step (line 95). It's only if you need to run rke2 agent to use more nodes running workloads.

2023-10-16 14:16 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +### BIOS Configuration
that's true. Something we talked some time ago. Adapt it just for the specific hardware. Thanks Tim

2023-10-16 14:24 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +For this example, we will assume the SLE Micro RT 5.4 operating system has been already installed on the baremetal host used to deploy the edge clusters. To verify the `Real Time Kernel` version used
added a note to explain how to download from SCC the RT image

2023-10-16 14:26 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +| isolcpu| 1-30,33-62| Isolate the cores 1-30 and 33-62                                                                     |
yes

2023-10-16 14:27 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +Modify the `/etc/default/grub` file to add the cpu cores to isolate. The next options have to be customized with your current hardware environment:
yes, you're right, not only cpu cores

2023-10-16 14:33 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +zypper in dpdk dpdk-tools pf-bb-config pciutils
I will only add the reference to the installation of these packages ok?

2023-10-16 14:33 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +`cpupower idle-set -d 3`
that's normal. no worries

2023-10-16 14:35 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +`cpupower idle-set -d 3`
I will add a note

2023-10-16 14:36 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +`cpupower idle-set -d 2`
same answer

2023-10-16 14:38 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +dpdk-devbind.py -b igb_uio 0000:8a:00.0`
good catch

2023-10-17 06:34 UTC, timirnich commented on blog/2023-07-28-flexran.md
> +zypper in dpdk dpdk-tools pf-bb-config pciutils
We need to document the entire process end-to-end. Everything a reader needs to do to reproduce our results. Absolutely everything.

2023-10-17 06:52 UTC, timirnich commented on blog/2023-07-28-flexran.md
> +### OS Configuration and Tunning
```suggestion
### OS Configuration and Tuning
```

2023-10-17 07:31 UTC, alknopfler commented on blog/2023-07-28-flexran.md
> +### OS Configuration and Tunning
thanks!

2023-10-20 07:11 UTC, timirnich commented on blog/2023-07-28-flexran.md
> +![img.png](2023-07-29-flexran-images/import-bios.png)
Please switch your browser to English and re-do the screenshot.

2023-10-23 12:23 UTC, merged