Add documentation for MetalLB svc in front of the KAPI
suse-edge/suse-edge.github.io pull request #69
Opened 2023-08-02 13:07 UTC by Kristian-ZH

Add documentation about how to set up a MetalLB Service in front of the Kubernetes API server

2023-08-02 13:19 UTC, rdoxenham requested changes
Great stuff... can we also maybe add a section for users that *already* have k3s deployed, where they would need to modify their setup to get MetalLB working in-front of their API?

2023-08-02 13:27 UTC, Kristian-ZH commented on docs/quickstart/metallb-kube-api.md
> +```
This is used later in the configurations that are made on the local machine.
For example the `IpAddressPool`:
```
spec:
  addresses:
  - ${VIP_SERVICE_IP}/32
```
or in the `sed` commands:
```
sed -i '' "s/${NODE_IP}/${VIP_SERVICE_IP}/g" ~/.kube/config
```

2023-08-02 13:34 UTC, rdoxenham commented on docs/quickstart/metallb-kube-api.md
> +```
Ahh, got it, would it not make sense to move it to just before this section rather than exporting it and then going elsewhere? No big deal, just want to make sure it's obvious to the reader.

2023-08-02 13:44 UTC, Kristian-ZH commented on docs/quickstart/metallb-kube-api.md
> +```
Fixed

2023-08-02 14:28 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +In this guide a MetalLB service will be used as an entrypoint for HA K3s cluster with 3 control-plane nodes.
```suggestion
In this guide a MetalLB service will be used to expose the K3s API externally on an HA K3s cluster with 3 control-plane nodes.
```

2023-08-02 14:29 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +To achieve this, Kubernetes Service of type `LoadBalancer` and Endpoints will be manually created. The Endpoints will keep the IPs of all VMs in the cluster.
```suggestion
To achieve this, a Kubernetes Service of type `LoadBalancer` and Endpoints will be manually created. The Endpoints will keep the IPs of all control plane nodes available in the cluster.
```

2023-08-02 14:30 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +In order for the Endpoint to be constantly synchronized with the events occurring in the cluster, a [Kubernetes Operator](https://github.com/suse-edge/endpoint-copier-operator) will be deployed, that
```suggestion
In order for the Endpoint to be continuously synchronized with the events occurring in the cluster (adding/removing a node or a node goes offline), the [Endpoint Copier Operator](https://github.com/suse-edge/endpoint-copier-operator) will be deployed. The operator monitors the events happening in the default `kubernetes` Endpoint and updates the managed one automatically to keep them in sync.
```

2023-08-02 14:31 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +  - Ensure that the VMs have different hostnames.
```suggestion
  - Ensure the hosts have different hostnames.
```

2023-08-02 14:32 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +sudo scp ${NODE_IP}:/etc/rancher/k3s/k3s.yaml ~/.kube/config && sed -i '' "s/127.0.0.1/${NODE_IP}/g" ~/.kube/config && chmod 600 ~/.kube/config
I guess sudo is not required here

2023-08-02 14:33 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +**NOTE:** Ensure that the IP addresses of the `ip-pool` IPAddressPool do not overlap with the IP addresses previously selected for the `LoadBalancer` service.
```suggestion
**NOTE:** Ensure that the IP addresses of the `ip-pool` IPAddressPool doesn't overlap with the IP addresses previously selected for the `LoadBalancer` service.
```

2023-08-02 14:33 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +Create a separate IP pool that will be used only for the managed Service.
```suggestion
Create a separate `IpAddressPool` that will be used only for the managed Service.
```

2023-08-02 14:34 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +The command above will deploy three different resources in the cluster:
```suggestion
The command above will deploy three different resources in the cluster:

```

2023-08-02 14:34 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +1. The `endpoint-copier-operator` operator Deployment with 2 replicas. One will be the leader and the other will just sleep.
```suggestion
1. The `endpoint-copier-operator` operator Deployment with 2 replicas. One replica will be the leader and the other will take over the leader role if needed.
```

2023-08-02 14:35 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +2. Service resource called `vip-kubernetes` in the `default` namespace that will be a copy of the `kubernetes` Service but from type `LoadBalancer`.
```suggestion
2. A Kubernetes service called `vip-kubernetes` in the `default` namespace that will be a copy of the `kubernetes` Service but from type `LoadBalancer`.
```

2023-08-02 14:35 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +3. Endpoints resource called `vip-kubernetes` in the `default` namespace that will be a copy of the `kubernetes` Endpoints.
```suggestion
3. An Endpoint resource called `vip-kubernetes` in the `default` namespace that will be a copy of the `kubernetes` Endpoint.
```

2023-08-02 14:35 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +Verify that the `kubernetes-vip` Service has a correct IP address:
```suggestion
Verify that the `kubernetes-vip` Service has the correct IP address:
```

2023-08-02 14:36 UTC, e-minguez commented on docs/quickstart/metallb-kube-api.md
> +### Join new control-plane nodes
```suggestion
### Add control-plane nodes
```

2023-08-02 14:37 UTC, e-minguez requested changes
Great work!!!
I've added some notes :) PTAL

2023-08-04 10:23 UTC, rdoxenham approved these changes
Looks great, thanks Kristian!

2023-08-04 10:56 UTC, e-minguez approved these changes
LGTM

2023-08-04 10:57 UTC, merged