Add guide how to install RKE2 cluster with SELinux enabled
suse-edge/suse-edge.github.io pull request #70
Opened 2023-08-21 10:33 UTC by Kristian-ZH

Add guide about how to install RKE2 cluster with SELinux enabled

2023-08-24 13:00 UTC, alknopfler commented on docs/quickstart/rke2-selinux.md
> +* 1 VM. Hint [SLE Micro on OSX on Apple Silicon (UTM)](https://suse-edge.github.io/docs/quickstart/slemicro-utm-aarch64) can be used.
maybe could be useful the info about minimum VM requirements to test it.

2023-08-24 13:00 UTC, alknopfler commented on docs/quickstart/rke2-selinux.md
> +* 1 VM. Hint [SLE Micro on OSX on Apple Silicon (UTM)](https://suse-edge.github.io/docs/quickstart/slemicro-utm-aarch64) can be used.
Only for UTM? Could be useful also the libvirt reference

2023-08-24 13:15 UTC, alknopfler commented on docs/quickstart/rke2-selinux.md
> +systemctl start rke2-server
```suggestion
systemctl enable --now rke2-server.service
```

2023-08-24 15:09 UTC, alknopfler requested changes
2 small changes to make it consistant with the previous review (Sorry but in the first one I forgot that 2 comments

2023-08-24 15:09 UTC, alknopfler commented on docs/quickstart/rke2-selinux.md
> +systemctl start rke2-server
```suggestion
# Enable and Start RKE2
systemctl enable --now rke2-server.service
```

2023-08-24 15:09 UTC, alknopfler commented on docs/quickstart/rke2-selinux.md
> +SSH back on the VM and execute the following commands:
```suggestion
Let's connect to the VM and run:
```

2023-09-05 08:39 UTC, e-minguez reviewed
Added some suggestions

2023-09-05 08:39 UTC, e-minguez commented on docs/quickstart/rke2-selinux.md
> +Now, the VM should be rebooted:
Is this really needed? Why?

2023-09-05 08:39 UTC, e-minguez commented on docs/quickstart/rke2-selinux.md
> +```
If a reboot is needed for whatever reason, this step can be done before the reboot so after the host has been rebooted, RKE2 is already up.

2023-09-05 08:39 UTC, e-minguez commented on docs/quickstart/rke2-selinux.md
> +### Installation for arm64 architecture
```suggestion
### Installation on arm64 architecture
```

2023-09-05 08:39 UTC, e-minguez commented on docs/quickstart/rke2-selinux.md
> +As there are no RPM builds for RKE2 on `arm64` architecture, the `Tarball` method will be used and the `rke2-selinux` policy will be installed manually.
```suggestion
As there are no RPM builds for RKE2 on `arm64` architecture, the `tarball` method will be used and the `rke2-selinux` policy will be installed manually.
```

2023-09-05 08:39 UTC, e-minguez commented on docs/quickstart/rke2-selinux.md
> +# Install SELinux Key and Package
```suggestion
# Install rpm-testing.rancher.io repository key and the rke2-selinux package
```

2023-09-05 08:39 UTC, e-minguez commented on docs/quickstart/rke2-selinux.md
> +# Install SELinux Key and Package
Is there a non testing repository available? it looks really odd to install a package from rpm-testing 😓

2023-09-05 08:39 UTC, e-minguez commented on docs/quickstart/rke2-selinux.md
> +```
Is this really needed? Why?

2023-09-05 08:47 UTC, Kristian-ZH commented on docs/quickstart/rke2-selinux.md
> +Now, the VM should be rebooted:
I think yes, because the command above installs multiple RPM packages

2023-09-05 08:50 UTC, Kristian-ZH commented on docs/quickstart/rke2-selinux.md
> +```
Again I think that when an RPM is installed on a snapshot based OS, a reboot is needed.
It even asks you for reboot after the installation

2023-09-05 08:54 UTC, e-minguez requested changes

2023-09-05 08:54 UTC, e-minguez commented on docs/quickstart/rke2-selinux.md
> +Now, the VM should be rebooted:
Then I think it should be a good idea to add the reason :)

```suggestion
Now, the VM should be rebooted for the transactional-update to finish properly:
```

2023-09-05 08:54 UTC, e-minguez commented on docs/quickstart/rke2-selinux.md
> +Now, the VM should be rebooted:
```suggestion
Now, the VM should be rebooted for the transactional-update to finish properly:
```

2023-09-05 08:54 UTC, e-minguez commented on docs/quickstart/rke2-selinux.md
> +```
See my suggestion above

2023-09-05 09:26 UTC, rdoxenham commented on docs/quickstart/rke2-selinux.md
> +mkdir -p /etc/rancher/rke2 && echo "selinux: true" > /etc/rancher/rke2/config.yaml
Suggest ">>" just incase the user has already created `/etc/rancher/rke2/config.yaml` and put additional parameters in here already.

2023-09-05 09:32 UTC, rdoxenham requested changes
Few minor things to add here, but generally looks great. Thanks!

2023-09-05 09:32 UTC, rdoxenham commented on docs/quickstart/rke2-selinux.md
> +> In this guide, RKE2 cluster will be installed with SELinux enabled.
```suggestion
> In this guide, we'll show you how to deploy an RKE2 cluster with SELinux enabled and enforcing.
```

2023-09-05 09:32 UTC, rdoxenham commented on docs/quickstart/rke2-selinux.md
> +* 1 VM. Hint [SLE Micro on OSX on Apple Silicon (UTM)](https://suse-edge.github.io/docs/quickstart/slemicro-utm-aarch64) or [SLE Micro on X86_64 on libvirt (virt-install)](https://suse-edge.github.io
```suggestion
* 1 VM. Hint [SLE Micro on OSX on Apple Silicon (UTM)](https://suse-edge.github.io/docs/quickstart/slemicro-utm-aarch64) or [SLE Micro on X86_64 on libvirt (virt-install)](https://suse-edge.github.io/docs/quickstart/slemicro-virt-install-x86_64) can be used as the base platform for validation here, but these instructions should work on any SLE Micro based system.
```

2023-09-05 09:32 UTC, rdoxenham commented on docs/quickstart/rke2-selinux.md
> +Once we've got the VM started and running, let's prepare the config to enable selinux mode in the RKE2 configuration file:
```suggestion
Once we've got the VM started and running, let's prepare the config to enable SELinux mode in the RKE2 configuration file:
```

2023-09-05 09:32 UTC, rdoxenham commented on docs/quickstart/rke2-selinux.md
> +mkdir -p /etc/rancher/rke2 && echo "selinux: true" > /etc/rancher/rke2/config.yaml
```suggestion
mkdir -p /etc/rancher/rke2 && echo "selinux: true" >> /etc/rancher/rke2/config.yaml
```

2023-09-05 09:32 UTC, rdoxenham commented on docs/quickstart/rke2-selinux.md
> +Now, the VM should be rebooted:
If you're rebooting immediately after, do you need the `--now` flag on the `systemctl enable` call? Is there advantage to doing this prior to the reboot?

2023-09-05 09:32 UTC, rdoxenham commented on docs/quickstart/rke2-selinux.md
> +As a second step, a RKE2 cluster will be installed, which will use the policy installed in the previous section.
```suggestion
As a second step, an RKE2 cluster will be installed, which will use the policy installed in the previous section.
```

2023-09-05 09:32 UTC, rdoxenham commented on docs/quickstart/rke2-selinux.md
> +mkdir -p /etc/rancher/rke2 && echo "selinux: true" > /etc/rancher/rke2/config.yaml
```suggestion
mkdir -p /etc/rancher/rke2 && echo "selinux: true" >> /etc/rancher/rke2/config.yaml
```

2023-09-05 10:48 UTC, rdoxenham approved these changes
LGTM

2023-09-05 10:48 UTC, merged